//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MetalSpec
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MetalSpecEntities : DbContext
    {
        public MetalSpecEntities()
            : base("name=MetalSpecEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Catalogue> Catalogue { get; set; }
        public virtual DbSet<Sortament> Sortament { get; set; }
        public virtual DbSet<Profiles> Profiles { get; set; }
        public virtual DbSet<Materials> Materials { get; set; }
        public virtual DbSet<FireResistTypes> FireResistTypes { get; set; }
    }
}
